### ISSUE TITLE
Complete German translation before release of 0.8.0?

### ISSUE THREAD

**Issue by jstuyts** [tatsuhiro-t/argparse4j#102]
All user messages are localizable now, and the texts for English, Dutch and Russian are complete. There is also a German resource bundle, but this has not been updated.

@Joerg-Schoemer: You provided the German translations that we have now. Do you have time to add and check the texts (42 in total) so German is complete and correct again?

**Comment by Joerg-Schoemer** [comment]
yes, I'can ;-)
