### ISSUE TITLE
Can't compile the last version

### ISSUE THREAD

**Issue by fuiuvjkrbxu** [tatsuhiro-t/argparse4j#105]
Hello, I imported the project in eclipse to compile the last version. 
last version .jar file release is for [dec 28 2017](https://github.com/tatsuhiro-t/argparse4j/releases). 

BTW I've got some error while exporting this project to a jar file. (I'm using eclipse 4.7.0, java 8)
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
please share a guide to compile and export it or release the last version.

thank you.

**Comment by jstuyts** [comment]
Do you use Eclipse or Maven to build the JAR? What is the error that you get?

I don't have GPG installed, so the Maven build will fail unless I add `-Dgpg.skip=true` to the command line.

**Comment by fuiuvjkrbxu** [comment]
Hi, I tried with mvn with `-Dgpg.skip=true` and executed `mvn clean package -Dgpg.skip=true`. it's done successfully and add these 3 jar files in my project.

![3jar](https://user-images.githubusercontent.com/30957470/29248191-8c65a62c-8027-11e7-83fe-22c1bb8e2f38.png)

but I can't use these libraries and I've get some error, I think I building it wrong. I glad if can share me more details, I'm a newbie in java.

![error](https://user-images.githubusercontent.com/30957470/29248204-be66b436-8027-11e7-9acc-51beea8ff726.png)

```
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	The method addArgument(String[]) in the type ArgumentContainer is not applicable for the arguments (String)

	at core.ArgsParse.start(ArgsParse.java:17)
```

**Comment by jstuyts** [comment]
I think you have the wrong Java source and target version for your project. It needs to be at least 1.5 for varargs. But argparse4j uses 1.6, so I think you should set it to 1.6 or higher. See [Setting the `-source` and `-target` of the Java Compiler](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html).

**Comment by fuiuvjkrbxu** [comment]
I'm using java 1.8
```
C:\Users\Bingo\Desktop\argparse4j-master>mvn -version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-04T00:09:06+04:30)
Maven home: C:\Program Files\apache-maven-3.5.0\bin\..
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_144\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by jstuyts** [comment]
Did you use the Eclipse Maven plug-in to import the project, or did you create an Eclipse project manually? You should use the Maven plug-in, and the plug-in should make sure that your Eclipse project is set up correctly.

Anyway, this is not an issues with argparse4j, so I am closing it.
