### ISSUE TITLE
Release 0.8.1 is not in Maven Repository

### ISSUE THREAD

**Issue by MartyIX** [tatsuhiro-t/argparse4j#108]
Hi,

I can see only 0.8.0 in Maven repository (https://mvnrepository.com/artifact/net.sourceforge.argparse4j/argparse4j). Is that intentional or is it a bug?

Regards,
Martin

**Comment by jstuyts** [comment]
It looks like it takes a while for mvnrepository.com to update its index. 0.8.1 is present in Maven Central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.sourceforge.argparse4j%22%20AND%20a%3A%22argparse4j%22
