### ISSUE TITLE
Turn ArgumentGroup into an interface extended by ArgumentParser and MutuallyExclusiveGroup

### ISSUE THREAD

**Issue by thejohnfreeman** [tatsuhiro-t/argparse4j#29]
I want to write general helpers that can add arguments to groups and parsers.

**Comment by SSNikolaevich** [comment]
ArgumentParser, ArgumentGroup and MutuallyExclusiveGroup share the same interface for add arguments:

    public interface ArgumentHolder {
        Argument addArgument(String... nameOrFlags);
    }

Having this interface will be good, for example, in case of dynamic parser building in runtime.

**Comment by jstuyts** [comment]
Fixed by #90. Introduced new interface `ArgumentContainer` implemented by `ArgumentParser`, `ArgumentGroup` and `MutuallyExclusiveGroup`.
