### ISSUE TITLE
nargs consumes required positional arguments

### ISSUE THREAD

**Issue by teoryn** [tatsuhiro-t/argparse4j#42]
An example of the expected behavior using python's argparse:

```
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('group', nargs='+')
>>> parser.add_argument('required')
>>> parser.parse_args(['1', '2', '3'])
Namespace(group=['1', '2'], required='3')
```

However, in argparse4j (0.4.3) the nargs='+' on the 'group' argument will consume 1,2,3 and there will not be a value left for the 'required' argument.

**Comment by tatsuhiro-t** [comment]
Sorry for the late response.  I did this intentionally.  While original argparse does the good job, but it seems to me that it is a bit complicated to work out how arguments are consumed.  So I simplified that; arguments are fully consumed from left to right.  This is easy to understand and there is no ambiguity here.

**Comment by teoryn** [comment]
Unfortunately it makes it difficult to implement a tool like 'cp' without manually separating the last element from the list of positional arguments. The nargs='+' argument can remain greedy minus the number of remaining required arguments.

**Comment by tatsuhiro-t** [comment]
Ah, true.  I missed that use case.  Probably, we have to reserve some arguments for positional args.

**Comment by tatsuhiro-t** [comment]
Finally, we fixed this issue.

**Comment by teoryn** [comment]
Thank you!
