### ISSUE TITLE
Can't represent an enum choices if they override toString

### ISSUE THREAD

**Issue by aJanuary** [tatsuhiro-t/argparse4j#43]
The usual method of having an enum argument is to use `ReflectArgumentType` for the type and `CollectionArgumentChoice` for the choice, passing in the enum values.

However, `CollectionArgumentChoice` calls `toString` on the values while `ReflectArgumentType` uses `valueOf`. If `toString` is overriden, `valueOf` won't be able to parse the result, making the help lie about what options are available.

```Java
enum Lang {
	PYTHON,
	JAVA,
	CPP {
		@Override
		public String toString() {
			return "C++";
		}
	}
}

public static void main(String[] args) {
	ArgumentParser parser = new ArgumentParserImpl("test");
	parser.addArgument("-lang")
		.choices(new CollectionArgumentChoice<Lang>(Lang.values()))
		.type(new ReflectArgumentType<Lang>(Lang.class));
	
	parser.printHelp();
	parser.parseArgsOrFail(new String[] { "-lang", "C++" });
}
```

Outputs:
```
usage: test [-h] [-lang {PYTHON,JAVA,C++}]

optional arguments:
  -h, --help             show this help message and exit
  -lang {PYTHON,JAVA,C++}
usage: test [-h] [-lang {PYTHON,JAVA,C++}]
test: error: argument -lang:  could  not  convert  'C++'  to  Lang (No enum
constant   com.test.Test.Lang.
C++)
```

The options I can see are:
 * `CollectionArgumentChoice` special cases enums, and call `name` instead (which would break backwards compatibility)
 * A new choice class is provided for enums.
 * A new type class is provided that is able to parse the string representations of enums. This would also allow people to provide a nicer command line interface for ugly enums by overriding toString.

I have implemented all three options, and can provide pull requests for any that you may be interested in.

**Comment by tatsuhiro-t** [comment]
We'd like to preserve backward compatibility, so 3rd one is better among them.
I can think of 4th option.  We already treat Enums in `ReflectArgumentType` specially, so instead of using `Enum.valueOf` there, we can iterate enum constants and call its `toString()` method and compare against input value, like so:

```diff
diff --git a/src/main/java/net/sourceforge/argparse4j/impl/type/ReflectArgumentType.java b/src/main/java/net/sourceforge/argparse4j/impl/type/ReflectArgumentType.java
index 61e303e..bb01af7 100644
--- a/src/main/java/net/sourceforge/argparse4j/impl/type/ReflectArgumentType.java
+++ b/src/main/java/net/sourceforge/argparse4j/impl/type/ReflectArgumentType.java
@@ -85,11 +85,18 @@ public class ReflectArgumentType<T> implements ArgumentType<T> {
         // It somehow can access private enum values, where normally T.valueOf()
         // cannot without setAccessible(true).
         if (type_.isEnum()) {
-            try {
-                return (T) Enum.valueOf((Class<Enum>) type_, value);
-            } catch (IllegalArgumentException e) {
-                throwArgumentParserException(parser, arg, value, e);
+            for (T v : type_.getEnumConstants()) {
+                if (v.toString().equals(value)) {
+                    return v;
+                }
             }
+            throwArgumentParserException(
+                    parser,
+                    arg,
+                    value,
+                    new IllegalArgumentException(String.format(
+                            TextHelper.LOCALE_ROOT, "No enum constant %s",
+                            value)));
         }
         Method m = null;
         try {
```

If `toString()` is not overridden, it returns the name of the constant itself.

BTW, your program can be written without `CollectionArgumentChoice` and `ReflectArgumentType`:

```java
    parser.addArgument("-lang").choices(Lang.values()).type(Lang.class);
```

Under the hood, the instantiations of these objects are made by the library.

**Comment by aJanuary** [comment]
re the choices and type overloads - neat. That's a lot nicer to read.

Your change to ReflectArgumentType is exactly what my 3rd option is doing, except without the new type.

Changing ReflectArgumentType would break backwards compatibility with anything that is currently using enums with overriden toStrings. Before it would accept "CPP", but now it only accepts "C++".

**Comment by tatsuhiro-t** [comment]
Agreed. Could you make a PR for your 3rd option?
