### ISSUE TITLE
Ignore unrecognized arguments ? 

### ISSUE THREAD

**Issue by vsraptor** [tatsuhiro-t/argparse4j#46]
Is there a way to ignore the unrecognized arguments instead of getting Exception.
I don't have control on what is passed to the app and the whole app breaks because I can not ignore the arguments I have not defined (which I have no way of knowing in advance).

(It seems none of the Java cmd line parsers can do this)
Let me know if there is solution ? thanks

PS> a non standard way of doing it will be OK, cause I have to otherwise manually pre-parse the arguments and get rid of the unwanted args, which will beat the purpose of using arg-parser in the first place and will impose many other limitations. thanks again for you patience

**Comment by tatsuhiro-t** [comment]
Basically we are in the same situation with http://stackoverflow.com/questions/24705637/linux-gnu-getopt-ignore-unknown-optional-arguments/24708049#24708049
We gather positional arguments scattered in command-line and distribute them according to nargs(), so if one of nargs('*') and nargs('+') is used, we have no away to treat some of them as unknown.
It seems python argparse achieve this by only considering contagious positional arguments, but we have not do this in this library.

**Comment by vsraptor** [comment]
Is there a way to parse the arguments, but catch the UrecognizedException and ignore it.
Currently it seems that if the UrecognizedException is thrown nothing is parsed at all, m'I correct ?

**Comment by tatsuhiro-t** [comment]
I've added ArgumentParser#parseKnownArgs() functions to parse known arguments only (see c986cadacd19bf5325ff0baed5efccaeadd51e9c).
As commit message says, this does not always work, if variable length positional arguments are used.  This is unavoidable with the current parsing rules.  Hope this works well for you.

**Comment by vsraptor** [comment]
thanks

**Comment by tatsuhiro-t** [comment]
Since we have ArgumentParser#parseKnownArgs(), this issue can be closed.
