### ISSUE TITLE
Make enum argument values case insensitive

### ISSUE THREAD

**Issue by asieira** [tatsuhiro-t/argparse4j#50]
If we use an argument of a type that is an enum, argparse4j with options `BLACK` and `RED`, the options will only work if the user specifies them in uppercase on the command-line. 

This is unfortunate since the Java language best practice for enum values is always all uppercase and that doesn't make for user-friendly CLI argument values.

How about allowing the values provided by the user to be case insensitive and still matching them to the correct enum value?

**Comment by tatsuhiro-t** [comment]
I agree that case insensitive match would increase usability.
FYI, we have Arguments.enumStringType() (http://argparse4j.sourceforge.net/usage.html#argument-type), which takes into account of toString override for enum types.  It does not perform case insensitive match (as it is the default behaviour for all other flags processing), but it can use the value of toString(), so you can supply the good name for enum.  But it  could be tedious to add toString for each enum, probably this is not ideal for you?

**Comment by asieira** [comment]
Unless I misunderstand how that functionality works, I wouldn't be able to accept both upper *and* lowercase, or mixed case, would I? So it's not exactly equivalent.

**Comment by tatsuhiro-t** [comment]
No.  Everything is case sensitive.  OK, then we already handle enum as special case, so let's make them case-insensitive.

**Comment by asieira** [comment]
:+1:

**Comment by tatsuhiro-t** [comment]
Thinking more carefully, although most users use uppercase name for enums in Java, nothing prevents us from doing like this:
```java
enum Foo {
   BAR, bar, Bar
}
```
This means case insensitive match could be ambiguous, and if existing code has these enums (unlikely?), then we may break their code.

Sounds like we cannot change the default behaviour.
I think you can create a custom ArgumentType to achieve this.

**Comment by asieira** [comment]
Yes, you do have a point, that situation needs to be properly handled.

Suggestion: how about a test for that scenario where more than one enum option would collide if compared in a case-insensitive fashion, and the system sticks to case-sensitiveness in those situations only?

**Comment by tatsuhiro-t** [comment]
It probably works, unless application started to add new enums which collides previous ones, then suddenly match goes case-sensitive.

**Comment by asieira** [comment]
You right, that could happen. I think that would be really really uncommon, though. How many enums in Java have you seen where the values were *not* in all caps? :)

My suggestion is to clearly document this behavior but still move forward, as this will help user-friendliness for the overwhelming majority of people that use enums with argparse4j.

What do you think?

**Comment by tatsuhiro-t** [comment]
We made couple of incompatible changes, but we really avoid that if possible.
Because we have no history to hear this kind of request before, I think it is safer to add dedicated ArgumentType sub class to handle case-insensitive match for enum.

**Comment by asieira** [comment]
Ok, let me know if there's anything I can do to help!

**Comment by jstuyts** [comment]
Sorry, I forgot to mention this issue in https://github.com/tatsuhiro-t/argparse4j/pull/80. Does the latter do what you need?

**Comment by asieira** [comment]
Yes, it does. Thank you! 🙇
