### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [tatsuhiro-t/argparse4j#56]
Hi
The following source files are without license headers:

./src/main/java/net/sourceforge/argparse4j/impl/type/EnumArgumentType.java
./src/main/java/net/sourceforge/argparse4j/internal/HelpScreenException.java
./src/main/java/net/sourceforge/argparse4j/internal/ParseState.java
./src/main/java/net/sourceforge/argparse4j/internal/UnrecognizedArgumentException.java
./src/main/java/net/sourceforge/argparse4j/internal/UnrecognizedCommandException.java

./src/test/java/net/sourceforge/argparse4j/ArgumentParsersTest.java
./src/test/java/net/sourceforge/argparse4j/helper/CJKTextWidthCounterTest.java
./src/test/java/net/sourceforge/argparse4j/helper/PrefixPatternTest.java
./src/test/java/net/sourceforge/argparse4j/helper/ReflectHelperTest.java
./src/test/java/net/sourceforge/argparse4j/helper/TextHelperTest.java
./src/test/java/net/sourceforge/argparse4j/impl/action/AppendArgumentActionTest.java
./src/test/java/net/sourceforge/argparse4j/impl/action/AppendConstArgumentActionTest.java
./src/test/java/net/sourceforge/argparse4j/impl/action/CountArgumentActionTest.java
./src/test/java/net/sourceforge/argparse4j/impl/choice/CollectionArgumentChoiceTest.java
./src/test/java/net/sourceforge/argparse4j/impl/choice/RangeArgumentChoiceTest.java
./src/test/java/net/sourceforge/argparse4j/impl/type/BooleanArgumentTypeTest.java
./src/test/java/net/sourceforge/argparse4j/impl/type/ConstructorArgumentTypeTest.java
./src/test/java/net/sourceforge/argparse4j/impl/type/EnumArgumentTypeTest.java
./src/test/java/net/sourceforge/argparse4j/impl/type/EnumStringArgumentTypeTest.java
./src/test/java/net/sourceforge/argparse4j/impl/type/FileArgumentTypeTest.java
./src/test/java/net/sourceforge/argparse4j/impl/type/ReflectArgumentTypeTest.java
./src/test/java/net/sourceforge/argparse4j/inf/NamespaceTest.java
./src/test/java/net/sourceforge/argparse4j/internal/ArgumentImplTest.java
./src/test/java/net/sourceforge/argparse4j/internal/ArgumentParserImplTest.java
./src/test/java/net/sourceforge/argparse4j/internal/SubparsersImplTest.java
./src/test/java/net/sourceforge/argparse4j/mock/MockArgument.java
./src/test/java/net/sourceforge/argparse4j/test/TestHelper.java

./src/site/sphinx/_static/default2.css

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by tatsuhiro-t** [comment]
Thank you for telling us.  All files in this repository are subject to MIT license.

**Comment by tatsuhiro-t** [comment]
Fix committed via c7f3708
