### ISSUE TITLE
org.apache.hadoop.fs.Path HdfsPathTypeArgument implementation

### ISSUE THREAD

**Issue by kpathak13** [tatsuhiro-t/argparse4j#59]
Since Hadoop developers are growing rapidly, I think this would be really beneficial for Hadoop developers to have `HdfsPathTypeArgument`.

**Comment by kpathak13** [comment]
I would like to contribute if this is something decided to be implemented.

**Comment by jstuyts** [comment]
Fixed by #88. If more Hadoop argument types are needed, please open a new issue.
