### ISSUE TITLE
Base options and sub commands

### ISSUE THREAD

**Issue by holtgrewe** [tatsuhiro-t/argparse4j#60]
Is it possible to support the following:

```
$ prog --base-option COMMAND --cmd-option1 --cmd-option2
```

Would I add `--base-option` to the base parser or to the sub parser?

**Comment by jstuyts** [comment]
@holtgrewe Did this answer your question/resolve your issue? If so, can you please close this issue? Thanks in advance.

**Comment by jstuyts** [comment]
The question has been answered. No code changes are needed.
