### ISSUE TITLE
How to get subcommand_name

### ISSUE THREAD

**Issue by fhennig** [tatsuhiro-t/argparse4j#61]
Hey,
in the python argparse version I get the selected subcommand from the namespace under the key "subcommand_name", but there is no such key in the Namespace I get from argparse4j. There aren't any similar keys either. How do I know which subcommand was invoked?

Cheers
Felix

**Comment by tatsuhiro-t** [comment]
Quoted from https://argparse4j.github.io/usage.html#sub-commands

> The alternative way is use Subparsers.dest() method. With this dest value, the selected command name is stored as an attribute:
> ```
public static void main(String[] args) {
    ArgumentParser parser = ArgumentParsers.newArgumentParser("prog");
    Subparsers subparsers = parser.addSubparsers().dest("subparser_name");
    Subparser subparser1 = subparsers.addParser("1");
    subparser1.addArgument("-x");
    Subparser subparser2 = subparsers.addParser("2");
    subparser2.addArgument("y");
    try {
        System.out.println(parser.parseArgs(args));
    } catch (ArgumentParserException e) {
        parser.handleError(e);
    }
}
```

>```
$ java Demo 2 frobble
Namespace(subparser_name=2, y=frobble)
```

**Comment by fhennig** [comment]
Okay it works thanks!
