### ISSUE TITLE
Require Java8

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/argparse4j#63]
We are going to require Java8 in the next release.
Previously, we just require good and old Java5.

I'm not sure how many people are looking at this issue, but we'd like to ask you that this is OK for you.
Java7 has been EOL quite some time, so Java8 requirement has good reason.  But projects have its own reason to stick to old standard.  We may reconsider our decision based on the input.

**Comment by kpathak13** [comment]
I think Java 8 is the way to go considering how programming paradigm has evolved in last decade and how community has perceived lambda and functional programming.

**Comment by dariober** [comment]
My 2p, a bit late as I've seen this issue now only. It seems to me that Java 7 is still popular (see this https://plumbr.eu/blog/java/java-version-and-vendor-data-analyzed-2016-edition, I have no idea how relevant this survey is). Anyway, If there is a good reason for argparse4j to use Java 8 functionalities, go for it. Otherwise I would prefer to stick to 7.

With the occasion, I used argparse4j quite a bit and it's great! Keep it up!

**Comment by marlowa** [comment]
Sorry to be an old wet blanket but I would like to see argparse4j support JDKs 6, 7 and 8. Yes, that's right, I am in an ancient environment where JDK 6 must be used. My client's product includes components that need to interface to third party proprietary jars that are for JDK 6, therefore we must be as well. I note that although the python argparse is very advanced compared to other parsers it was introduced at version 2.7 of python even though most people have moved to python 3. My client's customers are using RHEL 7.3 and this only has version 2.7. So it is just an unpleasant fact that in corporate environments old versions of python interpreters and JDKs still exist. In such environments the enterprise edition of java is mandated and the enterprise version of JDK 8 still hasn't come out yet. So only the most up to date clients have JDK 7, most are still using JDK 6 and none of them will use JDK 8 (yet).

**Comment by tatsuhiro-t** [comment]
Thank you for reply.  So far, the minimum requirement is JDK 6.  At the moment, JDK 6 can build argparse4j just fine.

**Comment by jstuyts** [comment]
The code will not be migrated to Java 8 at this moment. If a migration is desirable in the future, this can be reopened or a new issue can be created.
