### ISSUE TITLE
"optional arguments" confusing

### ISSUE THREAD

**Issue by holtgrewe** [tatsuhiro-t/argparse4j#65]
It is confusing that required options are described as "optional arguments".

IMO, naming them "required options" would be more clear.

**Comment by jstuyts** [comment]
I agree that it is confusing, but removing _optional_ will be confusing when positional arguments are present:

    usage: Foo --baz BAZ [--qux QUX] bar

    positional arguments:
      bar

    arguments:
      --baz BAZ
      --qux QUX

Is _other arguments_ a good alternative?

**Comment by holtgrewe** [comment]
Named arguments?

**Comment by jstuyts** [comment]
Fixed by https://github.com/tatsuhiro-t/argparse4j/pull/83.

**Comment by jstuyts** [comment]
Implemented in #83. If more changes are needed, please open a new issue.
