### ISSUE TITLE
Restructure project to allow for extension modules

### ISSUE THREAD

**Issue by jstuyts** [tatsuhiro-t/argparse4j#84]
There currently are 2 requests for argument types that would introduce unwanted requirements/dependencies:

* [java.nio.file.path PathArgumentType implementation](https://github.com/tatsuhiro-t/argparse4j/issues/58) requires Java 7.
* [org.apache.hadoop.fs.Path HdfsPathTypeArgument implementation](https://github.com/tatsuhiro-t/argparse4j/issues/59) would introduce a dependency on Hadoop.

These issues can be resolved in extension modules, so the main argparse4j module does not need Java 7 or dependencies on other projects. But for this the project structure has to be changed. I propose the following directory structure (in parentheses the artifact ID and the packaging are shown):

    <root> (argparse4j-root, POM)
    +-- extensions (argparse4j-extensions, POM)
    |   +-- java7 (argparse4j-java7, JAR)
    |   \-- hadoop (argparse4j-hdaoop, JAR)
    \-- main (argparse4j, JAR)

**Comment by tatsuhiro-t** [comment]
I agree with the proposed directory structure.  Thank you.

**Comment by jstuyts** [comment]
Great, thanks!
