### ISSUE TITLE
Migrate source to make use of 1.8 syntax

### ISSUE THREAD

**Issue by jstuyts** [tatsuhiro-t/argparse4j#97]
Once #93 and #95 have been merged, the source code can use 1.8 syntax without having to fear that classes not available in 1.6 or 1.7 are used by accident. At that moment, the code can be fully switched to Java 1.8 syntax, making it shorter and clearer.

**Comment by grimreaper** [comment]
I'm happy to take this on.

**Comment by jstuyts** [comment]
I will try to spend some time on this too in the coming weeks.

I think it would be a lot easier (i.e. less conflicts) for everybody if we could all work on the same branch, and push regularly, while migrating to Java 1.8 syntax. @tatsuhiro-t Would it be a good idea to set up a separate branch for this and give everybody who wants to help push rights to this branch? See https://help.github.com/articles/enabling-branch-restrictions/

**Comment by tatsuhiro-t** [comment]
I agree on your idea.

**Comment by jstuyts** [comment]
Can you create a branch and set the permissions? I do not have access to the settings. TIA

**Comment by tatsuhiro-t** [comment]
I made java1.8-syntax branch, but I could not find "Restrict who can push to this branch. "
It looks like it is available to the repository which belongs to an organization.
This repository still belongs to me, so the feature is missing.

**Comment by tatsuhiro-t** [comment]
I'm fine to move this repo to argparse4j organization.
If I understand the branch restrictions, we first have to add users to the organizations, and then restrict the branch who can push it.  And protect master branch for the limited collaborator.  Basically, collaborator with write permission can push to the any unprotected branches.

**Comment by jstuyts** [comment]
I cloned the repository and made both of you collaborators. I will also add other people if they want to help: https://github.com/jstuyts/argparse4j-java-1.8-syntax

Once the migration is done, we can do one big PR back to this project.

**Comment by tatsuhiro-t** [comment]
Thank you!

**Comment by jstuyts** [comment]
I am sorry, but I was mistaken. It is not possible to use a newer syntax with an older target. This seemed obvious to me, but apparently new syntax comes with class file changes that can't be loaded be earlier VMs.

I will revert my fork back to source levels matching the target levels.

Sorry for the noise.
